export type BenefitDefinition = {
    id: string,
    name: string,
    handle: string,
    period: number,
    period_type: string | null,
    absolute_expiry: string | null,
    description: string | null,
    internal_notes: string | null,
    meta: {[key: string]: any} | null,
    short_description: string | null,
    long_description: string | null,
    terms_conditions: string | null,
    earn_instructions: string | null,
    redeem_instructions_store: string | null,
    redeem_instructions_online: string | null,
    redeem_code_pos: string | null,
    redeem_code_online: string | null,
    icon: string | null,
    image_url: string | null,
    max_redemptions: number,
    is_extendable: boolean,
    is_assignable: boolean,
    is_reassignable: boolean,
    is_published: boolean,
    is_archived: boolean,
    tags: Array<string>,
    is_claimable: boolean,
    max_global_redemptions: number | null,
    total_global_redemptions: number| null,
    total_global_redemptions_remaining: number| null,
    total_global_created: number,
    claim_period_start_at: string | null,
    claim_period_end_at: string | null,
    claim_condition: string | null,
    is_reclaimable: boolean | null,
    notify_schedule_offset: number | null,
    notify_issue_offset_days: number | null,
    notify_issue_offset_hour: number | null,
    notify_remind_offset_days: number | null,
    notify_remind_offset_hour: number | null,
    notify_extend_offset_days: number | null,
    notify_extend_offset_hour: number | null,
    remind_target_id: number | null,
    extend_target_id: number | null,
    issue_target_id: number | null,
    end_at: string | null,
    total_allocations: string | null,
    total_allocations_remaining: string | null,
    force_allocation: string | null,
    created_at: string | null,
    updated_at: string | null,
    claim_timeframe: string | null,
    view_condition: string | null,
    allow_user_redeem: boolean | null,
    value: string | null,
    type: string | null,
}

export default BenefitDefinition;
