name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Setup Git
        run: |
          git config --local user.name "Oliver Arkade"
          git config --local user.email "oliver@arkade.com.au"

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: tsc && npx semantic-release